### PR TITLE
Fix TextAttributes property setting

### LINKED ISSUE #182: TextAttributes property handling
### Description

TextAttributes setters and equals/hashcode methods need to be reviewed for proper and consistent assignment and setting of values.

### Additional Information

This stems from the changes in pr #181

### PR DESCRIPTION
**Pull request by zglueck**
Closes #182 

### Description of the Change

This pull request corrects the setting of outline color properties and equivalency evaluation of the TextCacheKey object. A small set of test cases is included to verify the "happy-path" operation.

### Applicable Issues

#182

### CODE REVIEW

File: worldwind/src/main/java/gov/nasa/worldwind/render/RenderContext.java [hunk 1]
```diff
@@ -559,12 +559,15 @@ public boolean hasUserProperty(Object key) {
 
         public TextCacheKey set(String text, TextAttributes attributes) {
             this.text = text;
-            this.textColor = (attributes != null ? attributes.getTextColor() : null);
-            this.textSize = (attributes != null ? attributes.getTextSize() : 0);
-            this.typeface = (attributes != null ? attributes.getTypeface() : null);
-            this.enableOutline = (attributes != null && attributes.isEnableOutline());
-            this.outlineColor = (attributes != null ? attributes.getOutlineColor() : null);
-            this.outlineWidth = (attributes != null ? attributes.getOutlineWidth() : 0);
+            if (attributes != null) {
```
Comment (pdavidc) [inline worldwind/src/main/java/gov/nasa/worldwind/render/RenderContext.java]: Cache key properties need appropriate values when the attributes bundle is null. Consider the following state transitions:
• null -> non-null
• null -> null
• non-null -> null
• non-null -> non-null
Most properties can be assigned to either null or the appropriate value. Since we want to avoid repeated allocations, Color properties need to be assigned to null, assigned to a new instance and set, or just set, depending on the state transition.

File: worldwind/src/main/java/gov/nasa/worldwind/shape/TextAttributes.java [hunk 2]
```diff
@@ -104,7 +104,7 @@ public int hashCode() {
         result = 31 * result + (this.textSize != +0.0f ? Float.floatToIntBits(this.textSize) : 0);
         result = 31 * result + (this.typeface != null ? this.typeface.hashCode() : 0);
         result = 31 * result + (this.enableOutline ? 1 : 0);
-        result = 31 * result + (this.outlineColor != null ? this.outlineColor.hashCode() : 0);
+        result = 31 * result + this.outlineColor.hashCode();
```
Comment (pdavidc) [inline worldwind/src/main/java/gov/nasa/worldwind/shape/TextAttributes.java]: Nice catch. TextAttributes guarantees that textColor and outlineColor are non-null, correct?

Comment (zglueck) [reply worldwind/src/main/java/gov/nasa/worldwind/shape/TextAttributes.java]: @pdavidc , yes, the setter is protected by a null check. In the extreme, the field isn't private, so could be modified to null. I assumed that would be beyond the scope of our check, right?

Comment (pdavidc) [reply worldwind/src/main/java/gov/nasa/worldwind/shape/TextAttributes.java]: Yes, your assessment is correct. Android adopted the principle that we need not protect ourselves from poorly written subclasses.

File: worldwind/src/main/java/gov/nasa/worldwind/render/RenderContext.java (hunk 1 above)
Comment (zglueck) [reply worldwind/src/main/java/gov/nasa/worldwind/render/RenderContext.java]: You're right! I forgot about the scratch key utilization! I'll get it sorted out to account for the reuse case.

**Comment by zglueck** [comment]
@pdavidc , I've added what I believe to be the necessary allocations for the set method in 2348b7b

File: worldwind/src/main/java/gov/nasa/worldwind/render/RenderContext.java (hunk 1 above)
Comment (pdavidc) [reply worldwind/src/main/java/gov/nasa/worldwind/render/RenderContext.java]: I like your implementation. The branching is simple and reads very well.
